services:
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      NAME: ${DB_NAME} # Database name
      USER: ${DB_USER} # Database user name
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password

  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      DOMAIN: ${DOMAIN} # login.42.fr
      DB_NAME: ${DB_NAME} # Database name
      DB_USER: ${DB_USER} # Database user name
      TITLE: ${WORDPRESS_TITLE} # Inception
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    secrets:
      - credentials
      - db_password

  nginx:
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge


secrets:
  credentials:
    file: ./secrets/credentials.txt
  db_password:
    file: ./secrets/db_password.txt