services:
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      NAME: ${DB_NAME} # Database name
      USER: ${DB_USER} # Database user name
      PASSWORD: ${DB_PASSWORD} # Database user password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      DOMAIN: ${DOMAIN} # login.42.fr
      DB_NAME: ${DB_NAME} # Database name
      DB_USER: ${DB_USER} # Database user name
      DB_PASSWORD: ${DB_PASSWORD} # Database user password
      TITLE: ${WORDPRESS_TITLE} # Inception
      ADMIN_USER: ${WORDPRESS_ADMIN_USER} # Admin username
      ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL} # Admin email
      ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD} # Admin password
      USER_USER: ${WORDPRESS_USER} # Admin username
      USER_EMAIL: ${WORDPRESS_EMAIL} # Admin email
      USER_PASSWORD: ${WORDPRESS_PASSWORD} # Admin password
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
