FROM debian:bullseye

RUN apt-get update -y && apt-get upgrade -y
RUN	apt-get install mariadb-server -y

RUN mkdir -p /etc/sh/ && mkdir -p /var/run/mysqld && chown mysql:mysql /var/run/mysqld

COPY /conf/mariadb.conf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY /tools/init.sh /etc/tools/init.sh

RUN chmod +x /etc/tools/init.sh

CMD ["sh", "/etc/tools/init.sh"]