FROM	debian:bullseye

RUN		apt-get update -y && apt-get upgrade -y;
RUN 	apt-get install openssl net-tools nginx -y;
RUN 	mkdir -p /etc/nginx/ssl && mkdir -p /var/run/nginx
		
RUN		openssl req -x509 -nodes -out /etc/nginx/ssl/server.crt -keyout /etc/nginx/ssl/server.key -subj "/C=FR/ST=Alpes-Maritimes/L=Nice/O=42/OU=42/CN=maagosti.42.fr/UID=maagosti"

RUN		chmod 755 /var/www/html
RUN 	chown -R www-data:www-data /var/www/html

COPY	conf/nginx.conf /etc/nginx/nginx.conf

CMD 	[ "nginx", "-g", "daemon off;" ]